import React, { useState, useCallback, useRef } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { ScrollArea } from '@/components/ui/scroll-area';
import SmartChatConsultant from './SmartChatConsultant';
import FinancialHealthReport from './FinancialHealthReport';
import ProfitMaximizerDashboard from './ProfitMaximizerDashboard';
import DashboardHome from './DashboardHome';
import PriceCalculator from './PriceCalculator';
import { analyzeFileWithSmartDetection } from '@/lib/fashionAnalyzer';
import { smartReadFile } from '@/lib/smartFileReader';
import type { FashionAnalysisResult } from '@/lib/fashionAnalyzer';
import { useAuth } from '@/contexts/AuthContext';
import { useNavigate } from 'react-router-dom';
import { 
  Home, 
  Upload, 
  BarChart3, 
  MessageSquare, 
  FileText, 
  Download,
  Menu,
  X,
  LogOut,
  RefreshCw,
  TrendingUp,
  Package,
  Shield,
  DollarSign,
  Calculator,
  Sparkles,
  CheckCircle,
  ArrowRight,
  Zap,
  AlertTriangle
} from 'lucide-react';

interface DashboardState {
  isLoading: boolean;
  error: string | null;
  fashionAnalysis: FashionAnalysisResult | null;
  fileName: string | null;
  uploadDate: string | null;
  rawFileData: any[] | null;
  fileHeaders: string[] | null;
}

const DashboardLayout: React.FC = () => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [sidebarOpen, setSidebarOpen] = useState(window.innerWidth >= 1024);
  const [activeView, setActiveView] = useState<'home' | 'upload' | 'analytics' | 'consultant' | 'reports' | 'health' | 'profit' | 'calculator'>('upload');
  const [showUploadForm, setShowUploadForm] = useState(false);
  
  const [state, setState] = useState<DashboardState>({
    isLoading: false,
    error: null,
    fashionAnalysis: null,
    fileName: null,
    uploadDate: null,
    rawFileData: null,
    fileHeaders: null,
  });

  const handleFileUpload = useCallback(async (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    // Validate file type - now supports CSV and XLSX!
    const fileName = file.name.toLowerCase();
    if (!fileName.endsWith('.csv') && !fileName.endsWith('.xlsx') && !fileName.endsWith('.xls')) {
      setState((prev) => ({
        ...prev,
        error: 'Format file tidak didukung. Gunakan file CSV atau Excel (.xlsx/.xls)',
      }));
      return;
    }

    setState((prev) => ({ ...prev, isLoading: true, error: null }));

    try {
      // Read raw file data first for preview
      const rawData = await smartReadFile(file);
      
      // Use SMART detection - works for both CSV and XLSX!
      const result = await analyzeFileWithSmartDetection(file);

      setState((prev) => ({
        ...prev,
        fashionAnalysis: result,
        fileName: file.name,
        uploadDate: new Date().toLocaleString('id-ID'),
        rawFileData: rawData.data,
        fileHeaders: rawData.rawHeaders,
        isLoading: false,
      }));

      // Tetap di upload view setelah upload
      setActiveView('upload');
    } catch (err) {
      setState((prev) => ({
        ...prev,
        error: err instanceof Error ? err.message : 'Gagal membaca file. Pastikan format file benar.',
        isLoading: false,
      }));
    }
  }, []);

  const handleNewUpload = useCallback(() => {
    setState({
      isLoading: false,
      error: null,
      fashionAnalysis: null,
      fileName: null,
      uploadDate: null,
      rawFileData: null,
      fileHeaders: null,
    });
    setActiveView('upload');
    if (fileInputRef.current) fileInputRef.current.value = '';
  }, []);

  const handleDownloadReport = useCallback(() => {
    if (!state.fashionAnalysis) return;

    const { conclusion, insights, totalRevenue, totalUnits, averagePrice, products } = state.fashionAnalysis;

    const reportContent = `
===========================================
📊 LAPORAN ANALISIS FASHION SKIRO
===========================================

File: ${state.fileName || 'Unknown'}
Tanggal: ${state.uploadDate || 'Unknown'}
Total Produk: ${products.length}
Total Penjualan: ${totalUnits} unit
Total Revenue: Rp ${totalRevenue.toLocaleString('id-ID')}
Harga Rata-rata: Rp ${Math.round(averagePrice).toLocaleString('id-ID')}

===========================================
${conclusion}

===========================================
📈 INSIGHTS KUNCI:
===========================================
${insights.map((insight, idx) => `${idx + 1}. ${insight}`).join('\n')}

===========================================
Generated by Skiro - Fashion Deadstock Prevention System
===========================================
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `skiro-report-${Date.now()}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [state]);

  const handleLogout = () => {
    logout();
    navigate('/');
  };

  const menuItems = [
    { id: 'upload', icon: Upload, label: ' Upload Data Penjualan', view: 'upload' as const },
    { id: 'home', icon: BarChart3, label: ' Analisis Data Penjualan', view: 'home' as const, disabled: !state.fashionAnalysis },
    { id: 'profit', icon: DollarSign, label: ' Revenue Perusahaan', view: 'profit' as const, disabled: !state.fashionAnalysis },
    { id: 'consultant', icon: MessageSquare, label: ' AI konsultan Bisnis', view: 'consultant' as const, disabled: !state.fashionAnalysis },
    { id: 'calculator', icon: Calculator, label: ' Kalkulator Harga', view: 'calculator' as const },
  ];

  return (
    <div className="flex h-screen bg-gray-50 overflow-hidden relative">
      {/* Overlay untuk mobile - harus di luar sidebar */}
      {sidebarOpen && (
        <div 
          className="fixed inset-0 bg-black bg-opacity-50 lg:hidden z-40"
          onClick={() => setSidebarOpen(false)}
        />
      )}
      
      {/* Sidebar */}
      <aside className={`
        ${sidebarOpen ? 'w-64' : 'w-20'} 
        bg-gradient-to-b from-blue-950 via-blue-900 to-blue-950 text-white 
        transition-all duration-300 ease-in-out
        flex flex-col
        shadow-2xl
        fixed lg:relative
        z-50
        h-full
        ${sidebarOpen ? 'translate-x-0' : '-translate-x-full lg:translate-x-0'}
      `}>
        {/* Header */}
        <div className="p-4 border-b border-blue-800">
          <div className={`flex items-center ${sidebarOpen ? 'justify-between' : 'justify-center'}`}>
            {sidebarOpen && (
              <div className="flex items-center gap-2">
                <div className="w-10 h-10 rounded-lg bg-gradient-to-br from-blue-900 via-blue-800 to-blue-950 flex items-center justify-center shadow-lg">
                  <TrendingUp className="w-6 h-6 text-white" />
                </div>
                <div>
                  <h1 className="font-bold text-lg">SKIRO</h1>
                  <p className="text-xs text-blue-200"></p>
                </div>
              </div>
            )}
            <Button
              variant="ghost"
              size="icon"
              className="text-white hover:bg-blue-800"
              onClick={() => setSidebarOpen(!sidebarOpen)}
            >
              {sidebarOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}
            </Button>
          </div>
        </div>

        {/* User Info */}
        {sidebarOpen && user && (
          <div className="p-4 border-b border-blue-800 bg-blue-900/50">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-full bg-gradient-to-br from-blue-400 to-blue-600 flex items-center justify-center shadow-lg">
                <span className="font-bold text-white">{user.name?.charAt(0).toUpperCase()}</span>
              </div>
              <div className="flex-1 overflow-hidden">
                <p className="font-medium text-sm truncate">{user.name}</p>
                <p className="text-xs text-blue-200 truncate">{user.email}</p>
              </div>
            </div>
          </div>
        )}

        {/* File Info */}
        {sidebarOpen && state.fileName && (
          <div className="p-4 bg-blue-900/50 border-b border-blue-800">
            <div className="flex items-center gap-2 mb-1">
              <Package className="w-4 h-4 text-blue-200" />
              <p className="text-xs text-blue-200">File yang Lagi Dianalisis</p>
            </div>
            <p className="text-sm font-medium truncate">{state.fileName}</p>
            <p className="text-xs text-blue-200">{state.uploadDate}</p>
            {state.rawFileData && (
              <p className="text-xs text-blue-300 mt-1">📊 {state.rawFileData.length} baris data</p>
            )}
          </div>
        )}

        {/* Navigation Menu */}
        <ScrollArea className="flex-1 py-4">
          <nav className="space-y-1 px-2">
            {menuItems.map((item) => {
              const Icon = item.icon;
              const isActive = activeView === item.view;
              const isDisabled = item.disabled;
              
              return (
                <button
                  key={item.id}
                  onClick={() => {
                    if (!isDisabled) {
                      setActiveView(item.view);
                      // Auto close sidebar di mobile setelah klik menu
                      if (window.innerWidth < 1024) {
                        setSidebarOpen(false);
                      }
                    }
                  }}
                  disabled={isDisabled}
                  className={`
                    w-full flex items-center gap-3 px-3 py-3 rounded-lg
                    transition-all duration-200
                    ${isActive 
                      ? 'bg-white text-blue-950 shadow-lg font-bold' 
                      : isDisabled
                        ? 'text-blue-300 cursor-not-allowed opacity-50'
                        : 'text-white hover:bg-blue-800 hover:shadow-md'
                    }
                    ${!sidebarOpen && 'justify-center'}
                  `}
                >
                  <Icon className="w-5 h-5 flex-shrink-0" />
                  {sidebarOpen && <span className="font-medium">{item.label}</span>}
                </button>
              );
            })}
          </nav>
        </ScrollArea>

        {/* Bottom Actions */}
        <div className="p-4 border-t border-blue-800 space-y-2">
          {state.fashionAnalysis && (
            <>
              <Button
                variant="ghost"
                className="w-full text-white hover:bg-blue-800 justify-start"
                onClick={handleNewUpload}
              >
                <RefreshCw className="w-5 h-5 mr-2" />
                {sidebarOpen && 'Upload Lagi'}
              </Button>
              <Button
                variant="ghost"
                className="w-full text-white hover:bg-blue-800 justify-start"
                onClick={handleDownloadReport}
              >
                <Download className="w-5 h-5 mr-2" />
                {sidebarOpen && 'Download Laporan'}
              </Button>
            </>
          )}
          <Button
            variant="ghost"
            className="w-full text-white hover:bg-red-600 justify-start"
            onClick={handleLogout}
          >
            <LogOut className="w-5 h-5 mr-2" />
            {sidebarOpen && 'Keluar'}
          </Button>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 overflow-auto w-full">
        {/* Mobile Header */}
        <div className="lg:hidden bg-white border-b sticky top-0 z-40 px-4 py-3 flex items-center justify-between">
          <Button
            variant="ghost"
            size="icon"
            onClick={() => setSidebarOpen(true)}
          >
            <Menu className="w-6 h-6" />
          </Button>
          <div className="flex items-center gap-2">
            <TrendingUp className="w-6 h-6 text-blue-600" />
            <span className="font-bold text-lg">Skiro</span>
          </div>
          <div className="w-10" />
        </div>

        <div className="p-4 md:p-6 max-w-7xl mx-auto">
          {/* Home View - Dashboard Overview */}
          {activeView === 'home' && (
            <DashboardHome 
              analysis={state.fashionAnalysis} 
              onNavigate={(view) => setActiveView(view as any)} 
            />
          )}

          {/* Upload View */}
          {activeView === 'upload' && (
            <div className="space-y-8">
              {/* Welcome Hero Section - Only show if no data uploaded yet AND form not shown */}
              {!state.fashionAnalysis && !showUploadForm && (
                <>
                  {/* Feature Cards dengan animasi hover yang lebih menarik */}
                  <div className="grid md:grid-cols-3 gap-4">
                    <Card className="group relative overflow-hidden border border-blue-200 bg-gradient-to-br from-blue-50 to-white hover:shadow-xl hover:-translate-y-1 transition-all duration-300">
                      <div className="absolute top-0 right-0 w-24 h-24 bg-blue-200 rounded-full blur-3xl opacity-50 group-hover:opacity-100 transition-opacity" />
                      <CardHeader className="relative pb-3">
                        <div className="w-10 h-10 bg-gradient-to-br from-blue-600 to-blue-700 rounded-lg flex items-center justify-center mb-2 shadow-lg group-hover:scale-110 transition-transform">
                          <Package className="w-5 h-5 text-white" />
                        </div>
                        <CardTitle className="text-base font-bold text-gray-900">1. Upload Data</CardTitle>
                      </CardHeader>
                      <CardContent className="relative pt-0">
                        <p className="text-sm text-gray-600 leading-relaxed">
                          Mulai dengan upload file <strong>CSV</strong> atau <strong>Excel</strong> data penjualan toko kamu. 
                          Sistem bakal otomatis analisis dalam hitungan detik!
                        </p>
                        <div className="mt-3 flex items-center gap-2 text-xs text-blue-600 font-medium">
                          <span>Drag & Drop atau Klik</span>
                          <ArrowRight className="w-3 h-3 group-hover:translate-x-1 transition-transform" />
                        </div>
                      </CardContent>
                    </Card>

                    <Card className="group relative overflow-hidden border border-purple-200 bg-gradient-to-br from-purple-50 to-white hover:shadow-xl hover:-translate-y-1 transition-all duration-300">
                      <div className="absolute top-0 right-0 w-24 h-24 bg-purple-200 rounded-full blur-3xl opacity-50 group-hover:opacity-100 transition-opacity" />
                      <CardHeader className="relative pb-3">
                        <div className="w-10 h-10 bg-gradient-to-br from-purple-600 to-purple-700 rounded-lg flex items-center justify-center mb-2 shadow-lg group-hover:scale-110 transition-transform">
                          <BarChart3 className="w-5 h-5 text-white" />
                        </div>
                        <CardTitle className="text-base font-bold text-gray-900">2. Analisis Pintar</CardTitle>
                      </CardHeader>
                      <CardContent className="relative pt-0">
                        <p className="text-sm text-gray-600 leading-relaxed">
                          Sistem AI akan kasih tau produk mana yang <strong>laku keras</strong>, mana yang <strong>numpuk</strong>, 
                          dan strategi apa yang paling cocok untuk bisnis kamu!
                        </p>
                        <div className="mt-3 flex items-center gap-2 text-xs text-purple-600 font-medium">
                          <span>AI-Powered Insights</span>
                          <Sparkles className="w-3 h-3" />
                        </div>
                      </CardContent>
                    </Card>

                    <Card className="group relative overflow-hidden border border-green-200 bg-gradient-to-br from-green-50 to-white hover:shadow-xl hover:-translate-y-1 transition-all duration-300">
                      <div className="absolute top-0 right-0 w-24 h-24 bg-green-200 rounded-full blur-3xl opacity-50 group-hover:opacity-100 transition-opacity" />
                      <CardHeader className="relative pb-3">
                        <div className="w-10 h-10 bg-gradient-to-br from-green-600 to-green-700 rounded-lg flex items-center justify-center mb-2 shadow-lg group-hover:scale-110 transition-transform">
                          <MessageSquare className="w-5 h-5 text-white" />
                        </div>
                        <CardTitle className="text-base font-bold text-gray-900">3. Konsultasi AI</CardTitle>
                      </CardHeader>
                      <CardContent className="relative pt-0">
                        <p className="text-sm text-gray-600 leading-relaxed">
                          Tanya apapun ke <strong>AI Consultant</strong> tentang data toko kamu. 
                          Dapatkan rekomendasi bisnis personal yang actionable!
                        </p>
                        <div className="mt-3 flex items-center gap-2 text-xs text-green-600 font-medium">
                          <span>Chat dengan AI</span>
                          <MessageSquare className="w-3 h-3" />
                        </div>
                      </CardContent>
                    </Card>
                  </div>

                  {/* Tombol Mulai - Center & Premium */}
                  <div className="flex justify-center mt-1">
                    <Button
                      onClick={() => setShowUploadForm(true)}
                      className="bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 hover:from-blue-700 hover:via-indigo-700 hover:to-purple-700 text-white font-bold px-12 py-6 rounded-2xl shadow-2xl hover:shadow-blue-500/50 transition-all hover:scale-105 text-lg flex items-center gap-3"
                    >
                    
                      <span>Mulai Sekarang</span>
                      <ArrowRight className="w-6 h-6" />
                    </Button>
                  </div>
                </>
              )}

              {/* Upload Form - Show after clicking Mulai OR if data exists */}
              {(showUploadForm || state.fashionAnalysis) && (
                <>
              {/* Upload Section Header - Ultra Premium */}
              <div className="relative text-center py-3">
                {/* Background Glow Effect */}
                <div className="absolute inset-0 bg-gradient-to-r from-transparent via-blue-50/50 to-transparent blur-3xl" />
                
                <div className="relative space-y-3">
                  {/* Badge */}
                  <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-gradient-to-r from-blue-600/10 via-indigo-600/10 to-purple-600/10 border border-blue-200/50 backdrop-blur-sm shadow-lg">
                    <Sparkles className="w-3 h-3 text-blue-600 animate-pulse" />
                    <span className="text-xs font-semibold bg-gradient-to-r from-blue-600 to-indigo-600 bg-clip-text text-transparent">
                      {state.fashionAnalysis ? 'Upload File Baru' : 'Smart File Upload System'}
                    </span>
                  </div>
                  
                  {/* Title with Gradient */}
                  <h2 className="text-2xl md:text-3xl font-bold tracking-tight">
                    <span className="bg-gradient-to-r from-slate-900 via-blue-900 to-slate-900 bg-clip-text text-transparent">
                      {state.fashionAnalysis ? 'Upload Data Baru' : 'Upload Data Penjualan'}
                    </span>
                  </h2>
                  
                  {/* Subtitle */}
                  <p className="text-sm md:text-base text-slate-600 max-w-3xl mx-auto leading-relaxed">
                    {state.fashionAnalysis 
                      ? 'Analisis periode berbeda dengan upload file baru. Sistem akan memproses data dalam hitungan detik!' 
                      : 'Silahkan Upload file data penjualan CSV/Excel toko anda'
                    }
                  </p>
                  
                  {/* Active File Badge */}
                  {state.fileName && (
                    <div className="inline-flex items-center gap-2 px-3 py-2 bg-gradient-to-r from-green-50 to-emerald-50 border border-green-200 rounded-xl shadow-md">
                      <div className="flex items-center gap-1.5">
                        <CheckCircle className="w-4 h-4 text-green-600" />
                        <span className="text-xs font-medium text-green-900">File Aktif:</span>
                      </div>
                      <span className="text-xs font-bold text-green-700">{state.fileName}</span>
                      <div className="flex items-center gap-1 px-2 py-0.5 bg-white rounded-lg border border-green-200">
                        <div className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
                        <span className="text-[10px] font-semibold text-green-700">Ready</span>
                      </div>
                    </div>
                  )}
                </div>
              </div>

              {/* Download Template Section - World Class Design */}
              <div className="relative group">
                {/* Glow Effect */}
                <div className="absolute inset-0 bg-gradient-to-r from-green-500/20 via-emerald-500/20 to-green-500/20 rounded-2xl blur-xl opacity-50 group-hover:opacity-75 transition-opacity" />
                
                <Card className="relative border border-green-200/50 bg-gradient-to-br from-white via-green-50/30 to-emerald-50/30 backdrop-blur-sm shadow-lg overflow-hidden">
                  {/* Decorative Pattern */}
                  <div className="absolute inset-0 opacity-[0.03]">
                    <div className="absolute inset-0" style={{
                      backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%23000000' fill-opacity='1'%3E%3Cpath d='M36 34v-4h-2v4h-4v2h4v4h2v-4h4v-2h-4zm0-30V0h-2v4h-4v2h4v4h2V6h4V4h-4zM6 34v-4H4v4H0v2h4v4h2v-4h4v-2H6zM6 4V0H4v4H0v2h4v4h2V6h4V4H6z'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`
                    }} />
                  </div>
                  
                  <CardContent className="relative p-4">
                    <div className="flex flex-col lg:flex-row lg:items-center gap-4">
                      {/* Icon */}
                      <div className="flex-shrink-0">
                        <div className="relative">
                          <div className="absolute inset-0 bg-gradient-to-br from-green-500 to-emerald-600 rounded-2xl blur-lg opacity-50 animate-pulse" />
                          <div className="relative w-12 h-12 bg-gradient-to-br from-green-500 to-emerald-600 rounded-2xl flex items-center justify-center shadow-lg transform group-hover:scale-110 group-hover:rotate-3 transition-all duration-300">
                            <Download className="w-6 h-6 text-white" />
                          </div>
                        </div>
                      </div>
                      
                      {/* Content */}
                      <div className="flex-1 space-y-2">
                        <div className="flex items-center gap-2">
                          <h3 className="text-base font-bold text-slate-900">
                            Template Gratis Tersedia!
                          </h3>
                          <span className="px-2 py-0.5 bg-gradient-to-r from-green-500 to-emerald-500 text-white text-[10px] font-bold rounded-full shadow-sm">
                            FREE
                          </span>
                        </div>
                        
                        <p className="text-xs text-slate-600 leading-relaxed">
                          Belum punya format yang tepat? Download template CSV dari kami.
                          Isi data penjualan Anda dan langsung upload untuk analisis cepat!
                        </p>
                        
                        {/* Features */}
                        <div className="flex flex-wrap gap-1.5">
                          <div className="inline-flex items-center gap-1 px-2 py-1 bg-white/80 backdrop-blur-sm rounded-lg border border-green-200/50 shadow-sm">
                            <CheckCircle className="w-3 h-3 text-green-600" />
                            <span className="text-[10px] font-semibold text-slate-700">Support Semua Size</span>
                          </div>
                          <div className="inline-flex items-center gap-1 px-2 py-1 bg-white/80 backdrop-blur-sm rounded-lg border border-green-200/50 shadow-sm">
                            <CheckCircle className="w-3 h-3 text-green-600" />
                            <span className="text-[10px] font-semibold text-slate-700">CSV & Excel</span>
                          </div>
                          <div className="inline-flex items-center gap-1 px-2 py-1 bg-white/80 backdrop-blur-sm rounded-lg border border-green-200/50 shadow-sm">
                            <Sparkles className="w-3 h-3 text-green-600" />
                            <span className="text-[10px] font-semibold text-slate-700">Format mudah di mengerti</span>
                          </div>
                        </div>
                      </div>
                      
                      {/* CTA Button */}
                      <div className="flex-shrink-0">
                        <a 
                          href="/template-penjualan.csv" 
                          download="template-penjualan-skiro.csv"
                        >
                          <Button className="group/btn relative bg-gradient-to-r from-green-600 via-emerald-600 to-green-600 hover:from-green-700 hover:via-emerald-700 hover:to-green-700 text-white shadow-lg hover:shadow-xl transition-all duration-300 px-4 py-2 text-xs font-bold overflow-hidden">
                            <div className="absolute inset-0 bg-white/20 translate-y-full group-hover/btn:translate-y-0 transition-transform duration-300" />
                            <Download className="w-3.5 h-3.5 mr-1.5 group-hover/btn:animate-bounce" />
                            <span className="relative">Download Template</span>
                          </Button>
                        </a>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              </div>

              {/* Upload Zone - Ultra Premium Glassmorphism Design */}
              <div className="relative group/upload">
                {/* Outer Ambient Glow */}
                <div className="absolute -inset-6 bg-gradient-to-r from-blue-600/10 via-purple-600/10 to-indigo-600/10 rounded-[3rem] blur-3xl opacity-60 group-hover/upload:opacity-100 transition-all duration-700" />
                <div className="absolute -inset-4 bg-gradient-to-br from-blue-500/5 via-indigo-500/5 to-purple-500/5 rounded-[2.5rem] blur-2xl group-hover/upload:blur-3xl transition-all duration-500" />
                
                <Card className="relative border border-white/20 shadow-2xl overflow-hidden bg-gradient-to-br from-white/95 via-blue-50/80 to-indigo-50/60 backdrop-blur-xl">
                  {/* Decorative Elements */}
                  <div className="absolute top-0 right-0 w-64 h-64 bg-gradient-to-br from-blue-500/10 to-purple-500/10 rounded-full blur-3xl" />
                  <div className="absolute bottom-0 left-0 w-48 h-48 bg-gradient-to-tr from-indigo-500/10 to-blue-500/10 rounded-full blur-3xl" />
                  
                  <CardContent className="relative p-6">
                    <div 
                      className="group/zone relative flex flex-col items-center justify-center w-full min-h-[350px] border-2 border-dashed border-blue-300/50 rounded-3xl cursor-pointer bg-gradient-to-br from-white/80 via-blue-50/40 to-indigo-50/30 backdrop-blur-md hover:border-blue-400/70 hover:bg-gradient-to-br hover:from-blue-50/70 hover:via-indigo-50/50 hover:to-purple-50/40 hover:shadow-xl hover:shadow-blue-500/20 transition-all duration-700 ease-out overflow-hidden hover:scale-[1.01]"
                      onClick={() => fileInputRef.current?.click()}
                      onDragOver={(e) => {
                        e.preventDefault();
                        e.currentTarget.classList.add('border-blue-600', 'bg-blue-100', 'scale-[1.02]');
                      }}
                      onDragLeave={(e) => {
                        e.currentTarget.classList.remove('border-blue-600', 'bg-blue-100', 'scale-[1.02]');
                      }}
                      onDrop={(e) => {
                        e.preventDefault();
                        e.currentTarget.classList.remove('border-blue-600', 'bg-blue-100', 'scale-[1.02]');
                        const files = e.dataTransfer.files;
                        if (files.length > 0 && fileInputRef.current) {
                          const dt = new DataTransfer();
                          dt.items.add(files[0]);
                          fileInputRef.current.files = dt.files;
                          fileInputRef.current.dispatchEvent(new Event('change', { bubbles: true }));
                        }
                      }}
                    >
                      {/* Animated Grid Background */}
                      <div className="absolute inset-0 opacity-5">
                        <div className="absolute inset-0" style={{
                          backgroundImage: `url("data:image/svg+xml,%3Csvg width='60' height='60' viewBox='0 0 60 60' xmlns='http://www.w3.org/2000/svg'%3E%3Cg fill='none' fill-rule='evenodd'%3E%3Cg fill='%232563eb' fill-opacity='1'%3E%3Ccircle cx='30' cy='30' r='2'/%3E%3C/g%3E%3C/g%3E%3C/svg%3E")`,
                          backgroundSize: '30px 30px'
                        }} />
                      </div>
                      
                      <div className="relative flex flex-col items-center justify-center py-8 px-4 pointer-events-none z-10">
                        {/* Animated Upload Icon with 3D Effect */}
                        <div className="relative mb-6">
                          {/* Multi-layer ambient glow */}
                          <div className="absolute inset-0 bg-blue-500/40 rounded-2xl blur-3xl opacity-50 group-hover/zone:opacity-90 transition-all duration-700 animate-pulse" />
                          <div className="absolute inset-0 bg-indigo-500/30 rounded-2xl blur-2xl opacity-30 group-hover/zone:opacity-70 transition-all duration-700" style={{animationDelay: '0.3s'}} />
                          <div className="absolute inset-0 bg-purple-500/20 rounded-2xl blur-xl opacity-20 group-hover/zone:opacity-60 transition-all duration-700" style={{animationDelay: '0.6s'}} />
                          
                          {/* Icon Container with 3D effect */}
                          <div className="relative w-24 h-24 bg-gradient-to-br from-blue-600 via-indigo-600 to-purple-600 rounded-2xl flex items-center justify-center shadow-2xl group-hover/zone:scale-110 group-hover/zone:rotate-6 transition-all duration-700 ease-out transform-gpu" style={{transformStyle: 'preserve-3d'}}>
                            <div className="absolute inset-0 bg-gradient-to-tr from-white/30 via-white/10 to-transparent rounded-2xl" />
                            <div className="absolute inset-0 bg-gradient-to-bl from-transparent via-black/5 to-black/20 rounded-2xl" />
                            <Upload className="relative w-12 h-12 text-white drop-shadow-2xl group-hover/zone:scale-110 transition-transform duration-500" />
                          </div>
                          
                          {/* Floating Particles */}
                          <div className="absolute -top-2 -right-2 w-6 h-6 bg-blue-500 rounded-full opacity-60 animate-ping" />
                          <div className="absolute -bottom-2 -left-2 w-4 h-4 bg-purple-500 rounded-full opacity-60 animate-ping" style={{animationDelay: '0.3s'}} />
                        </div>
                        
                        {/* Text Content with Enhanced Typography */}
                        <div className="text-center space-y-3 mb-6">
                          <h3 className="text-2xl md:text-3xl font-black tracking-tight">
                            <span className="bg-gradient-to-r from-blue-700 via-indigo-600 to-purple-600 bg-clip-text text-transparent group-hover/zone:from-blue-600 group-hover/zone:via-indigo-500 group-hover/zone:to-purple-500 transition-all duration-500 drop-shadow-sm">
                              Drop File di Sini
                            </span>
                          </h3>
                          <p className="text-sm md:text-base text-slate-600/90 max-w-xl leading-relaxed font-medium">
                            atau <span className="text-blue-600 font-semibold">klik untuk memilih</span> file dari komputer Anda
                          </p>
                        </div>
                        
                        {/* Premium Upload Button */}
                        <div className="relative group/btn mb-6">
                          <div className="absolute -inset-1 bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 rounded-2xl blur-xl opacity-60 group-hover/btn:opacity-100 transition-all duration-500" />
                          <div className="relative px-8 py-4 bg-gradient-to-r from-blue-600 via-indigo-600 to-purple-600 hover:from-blue-700 hover:via-indigo-700 hover:to-purple-700 text-white rounded-2xl shadow-2xl hover:shadow-blue-500/50 text-sm md:text-base font-bold group-hover/btn:scale-105 transition-all duration-500 flex items-center gap-3 border border-white/20">
                            <Upload className="w-5 h-5 group-hover/btn:scale-110 group-hover/btn:-rotate-12 transition-all duration-500" />
                            <span className="tracking-wide">Pilih File dari Komputer</span>
                            <ArrowRight className="w-4 h-4 group-hover/btn:translate-x-1 transition-transform duration-300" />
                          </div>
                        </div>
                        
                        {/* Supported Formats - Premium Badges */}
                        <div className="flex flex-wrap items-center justify-center gap-3">
                          <div className="group/format flex items-center gap-2 px-3 py-2 bg-white/95 backdrop-blur-md rounded-xl border border-green-200/60 shadow-lg hover:shadow-xl hover:scale-105 transition-all duration-300">
                            <div className="w-10 h-10 bg-gradient-to-br from-green-500 to-emerald-600 rounded-lg flex items-center justify-center shadow-md group-hover/format:scale-110 transition-transform duration-300">
                              <FileText className="w-5 h-5 text-white" />
                            </div>
                            <div className="text-left">
                              <p className="text-xs font-bold text-slate-800">CSV File</p>
                              <p className="text-[10px] text-slate-500 font-medium">.csv format</p>
                            </div>
                            <div className="w-2 h-2 bg-green-500 rounded-full animate-pulse" />
                          </div>
                          
                          <div className="group/format flex items-center gap-2 px-3 py-2 bg-white/95 backdrop-blur-md rounded-xl border border-blue-200/60 shadow-lg hover:shadow-xl hover:scale-105 transition-all duration-300">
                            <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-lg flex items-center justify-center shadow-md group-hover/format:scale-110 transition-transform duration-300">
                              <FileText className="w-5 h-5 text-white" />
                            </div>
                            <div className="text-left">
                              <p className="text-xs font-bold text-slate-800">Excel File</p>
                              <p className="text-[10px] text-slate-500 font-medium">.xlsx, .xls</p>
                            </div>
                            <div className="w-2 h-2 bg-blue-500 rounded-full animate-pulse" />
                          </div>
                          
                          <div className="flex items-center gap-1.5 px-2 py-1.5 bg-white/90 backdrop-blur-sm rounded-lg border border-yellow-200/50 shadow-md">
                            <div className="w-8 h-8 bg-gradient-to-br from-yellow-500 to-orange-500 rounded-md flex items-center justify-center shadow-sm">
                              <Zap className="w-4 h-4 text-white" />
                            </div>
                            <div className="text-left">
                              <p className="text-[10px] font-semibold text-slate-700">Auto Detect</p>
                              <p className="text-[9px] text-slate-500">Smart AI</p>
                            </div>
                          </div>
                        </div>
                        
                        {/* Info Text */}
                        <p className="mt-4 text-xs text-slate-500 max-w-md text-center">
                          <Sparkles className="w-3 h-3 inline mr-1" />
                          AI kami akan otomatis mendeteksi struktur data file anda
                        </p>
                      </div>
                      
                      <input
                        ref={fileInputRef}
                        type="file"
                        className="hidden"
                        accept=".csv,.xlsx,.xls"
                        onChange={handleFileUpload}
                        disabled={state.isLoading}
                      />
                    </div>
                  </CardContent>

                  {/* Loading State - Premium Animation */}
                  {state.isLoading && (
                    <div className="relative p-12 bg-gradient-to-br from-blue-50 via-indigo-50 to-purple-50 border-t-4 border-blue-500 overflow-hidden">
                      {/* Animated Background */}
                      <div className="absolute inset-0">
                        <div className="absolute top-0 left-1/4 w-64 h-64 bg-blue-400/20 rounded-full blur-3xl animate-pulse" />
                        <div className="absolute bottom-0 right-1/4 w-64 h-64 bg-purple-400/20 rounded-full blur-3xl animate-pulse" style={{animationDelay: '1s'}} />
                      </div>
                      
                      <div className="relative text-center space-y-6">
                        {/* Spinner */}
                        <div className="relative inline-flex items-center justify-center">
                          {/* Outer Ring */}
                          <div className="absolute animate-spin rounded-full h-24 w-24 border-4 border-blue-200 border-t-blue-600"></div>
                          {/* Middle Ring */}
                          <div className="absolute animate-spin rounded-full h-20 w-20 border-4 border-transparent border-t-indigo-500" style={{animationDuration: '1.5s', animationDirection: 'reverse'}}></div>
                          {/* Center Icon */}
                          <div className="relative z-10 w-16 h-16 bg-gradient-to-br from-blue-600 to-indigo-600 rounded-full flex items-center justify-center shadow-xl">
                            <Sparkles className="w-8 h-8 text-white animate-pulse" />
                          </div>
                        </div>
                        
                        {/* Text */}
                        <div className="space-y-3">
                          <h4 className="text-2xl md:text-3xl font-black bg-gradient-to-r from-blue-700 via-indigo-600 to-purple-600 bg-clip-text text-transparent">
                            AI Sedang Menganalisis File Anda
                          </h4>
                          <p className="text-lg text-slate-600 max-w-md mx-auto">
                            Sistem cerdas kami memproses data penjualan dengan teknologi machine learning terkini
                          </p>
                        </div>
                        
                        {/* Animated Dots */}
                        <div className="flex items-center justify-center gap-2">
                          <div className="w-3 h-3 bg-blue-600 rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                          <div className="w-3 h-3 bg-indigo-600 rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                          <div className="w-3 h-3 bg-purple-600 rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                        </div>
                        
                        {/* Progress Steps */}
                        <div className="mt-8 max-w-md mx-auto space-y-3">
                          {[
                            { icon: FileText, text: 'Membaca struktur file', delay: '0s' },
                            { icon: Sparkles, text: 'Deteksi kolom otomatis', delay: '0.5s' },
                            { icon: BarChart3, text: 'Analisis pola data', delay: '1s' },
                          ].map((step, idx) => (
                            <div 
                              key={idx}
                              className="flex items-center gap-3 p-3 bg-white/80 backdrop-blur-sm rounded-xl border border-blue-200/50 shadow-sm animate-pulse"
                              style={{animationDelay: step.delay}}
                            >
                              <div className="w-10 h-10 bg-gradient-to-br from-blue-500 to-indigo-600 rounded-lg flex items-center justify-center">
                                <step.icon className="w-5 h-5 text-white" />
                              </div>
                              <span className="text-sm font-semibold text-slate-700">{step.text}</span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  )}

                  {/* Error State - Premium Design */}
                  {state.error && (
                    <div className="relative p-8 bg-gradient-to-br from-red-50 via-orange-50 to-red-50 border-t-4 border-red-500 overflow-hidden">
                      <div className="absolute inset-0 opacity-10">
                        <div className="absolute inset-0" style={{
                          backgroundImage: `url("data:image/svg+xml,%3Csvg width='40' height='40' viewBox='0 0 40 40' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M0 0h40v40H0V0zm20 20L0 0l20 20 20-20-20 20z' fill='%23ef4444' fill-opacity='0.4' fill-rule='evenodd'/%3E%3C/svg%3E")`
                        }} />
                      </div>
                      
                      <Alert variant="destructive" className="relative border-2 border-red-300 bg-white/90 backdrop-blur-sm shadow-xl">
                        <div className="flex items-start gap-4">
                          <div className="flex-shrink-0 w-12 h-12 bg-gradient-to-br from-red-500 to-red-600 rounded-xl flex items-center justify-center shadow-lg">
                            <AlertTriangle className="w-6 h-6 text-white" />
                          </div>
                          <div className="flex-1">
                            <AlertDescription className="text-base text-slate-800">
                              <p className="font-bold text-lg text-red-700 mb-2">Oops! Terjadi Kesalahan</p>
                              <p className="leading-relaxed">{state.error}</p>
                              <div className="mt-4 p-3 bg-red-50 rounded-lg border border-red-200">
                                <p className="text-sm text-red-800">
                                  <strong>Tips:</strong> Pastikan file CSV/Excel Anda memiliki kolom yang sesuai (Produk, Size, Harga, Quantity).
                                </p>
                              </div>
                            </AlertDescription>
                          </div>
                        </div>
                      </Alert>
                    </div>
                  )}
                </Card>
              </div>

              {/* Shimmer Animation CSS */}
              <style>{`
                @keyframes shimmer {
                  0% { background-position: -200% 0; }
                  100% { background-position: 200% 0; }
                }
                .bg-grid-pattern {
                  background-image: 
                    linear-gradient(to right, #e5e7eb 1px, transparent 1px),
                    linear-gradient(to bottom, #e5e7eb 1px, transparent 1px);
                  background-size: 20px 20px;
                }
              `}</style>
              </>
              )}

              {/* File Preview Section */}
              {state.rawFileData && state.fileHeaders && state.fileName && (
                <Card className="border-2 border-blue-200">
                  <CardHeader className="bg-blue-50">
                    <div className="flex items-center justify-between">
                      <CardTitle className="text-blue-900 flex items-center gap-2">
                        <FileText className="w-5 h-5" />
                        Preview: {state.fileName}
                      </CardTitle>
                      <div className="text-sm text-blue-700">
                        📊 {state.rawFileData.length} baris data • Upload: {state.uploadDate}
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent className="pt-6">
                    <div className="space-y-4">
                      <Alert className="bg-green-50 border-green-200">
                        <AlertDescription className="text-green-900">
                          <strong>✅ File berhasil diupload!</strong> Sistem sudah analisis {state.rawFileData.length} baris data. 
                          Scroll kebawah untuk liat preview datanya atau klik menu lain untuk liat hasil analisis lengkap.
                        </AlertDescription>
                      </Alert>

                      {/* Data Table Preview */}
                      <div className="border rounded-lg overflow-hidden">
                        <div className="overflow-x-auto max-h-96 overflow-y-auto">
                          <table className="min-w-full divide-y divide-gray-200">
                            <thead className="bg-gray-50 sticky top-0 z-10">
                              <tr>
                                <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider bg-gray-100">
                                  #
                                </th>
                                {state.fileHeaders.map((header, idx) => (
                                  <th 
                                    key={idx} 
                                    className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider bg-gray-100"
                                  >
                                    {header || `Column ${idx + 1}`}
                                  </th>
                                ))}
                              </tr>
                            </thead>
                            <tbody className="bg-white divide-y divide-gray-200">
                              {state.rawFileData.slice(0, 50).map((row, rowIdx) => (
                                <tr key={rowIdx} className={rowIdx % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
                                  <td className="px-4 py-3 text-sm text-gray-900 font-medium">
                                    {rowIdx + 1}
                                  </td>
                                  {state.fileHeaders.map((header, colIdx) => (
                                    <td 
                                      key={colIdx} 
                                      className="px-4 py-3 text-sm text-gray-700 whitespace-nowrap"
                                    >
                                      {row[colIdx] !== null && row[colIdx] !== undefined ? String(row[colIdx]) : '-'}
                                    </td>
                                  ))}
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                        
                        {state.rawFileData.length > 50 && (
                          <div className="bg-gray-50 px-4 py-3 text-center text-sm text-gray-600 border-t">
                            Menampilkan 50 dari {state.rawFileData.length} baris data. 
                            Untuk melihat semua data, download file asli.
                          </div>
                        )}
                      </div>

                      <div className="flex gap-3">
                        <Button 
                          onClick={() => setActiveView('home')} 
                          className="flex-1 bg-blue-600 hover:bg-blue-700"
                        >
                          
                          Lihat analisis data penjualan
                        </Button>
                        <Button 
                          
                          onClick={handleNewUpload}
                          variant="outline"
                          className="border-red-300 text-red-600 hover:bg-red-50"
                        >
                          <RefreshCw className="w-4 h-4 mr-2" />
                          Upload File Lain
                        </Button>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              )}

            </div>
          )}

          {/* Profit Maximizer View - WORLD CLASS PROFIT SYSTEM */}
          {activeView === 'profit' && state.fashionAnalysis && (
            <div className="space-y-6">
              <ProfitMaximizerDashboard analysis={state.fashionAnalysis} />
            </div>
          )}

          {/* Calculator View */}
          {activeView === 'calculator' && (
            <div className="space-y-6">
              <PriceCalculator />
            </div>
          )}

          {/* Consultant View */}
          {activeView === 'consultant' && state.fashionAnalysis && (
            <div className="space-y-6">
              <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-blue-950 via-blue-900 to-blue-800 p-8 shadow-2xl animate-in fade-in slide-in-from-top duration-700">
                {/* Animated Background Effect */}
                <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent animate-shimmer" 
                     style={{
                       backgroundSize: '200% 100%',
                       animation: 'shimmer 3s infinite'
                     }} />
                
                {/* Content */}
                <div className="relative z-10">
                  <div className="flex items-center gap-4 mb-4">
                    <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-blue-400 to-blue-600 flex items-center justify-center shadow-xl animate-pulse">
                      <MessageSquare className="w-8 h-8 text-white" />
                    </div>
                    <div>
                      <h1 className="text-4xl md:text-5xl font-black text-transparent bg-clip-text bg-gradient-to-r from-white via-blue-100 to-blue-200 drop-shadow-lg">
                        Konsultan Bisnis AI
                      </h1>
                    </div>
                  </div>
                  <p className="text-blue-100 text-lg md:text-xl leading-relaxed max-w-3xl">
                   <span className="font-semibold text-white">Anda bisa tanya apa aja!</span> Strategi bisnis fashion, cara optimasi stok, teknik marketing, analisis kompetitor, atau apapun ! AI kami siap bantu dengan jawaban yang <span className="text-cyan-300 font-bold">akurat & actionable!</span>
                  </p>
                </div>

                {/* Decorative Elements */}
                <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/10 rounded-full blur-3xl" />
                <div className="absolute bottom-0 left-0 w-48 h-48 bg-purple-500/10 rounded-full blur-3xl" />
              </div>

              {/* Shimmer Animation Keyframe */}
              <style>{`
                @keyframes shimmer {
                  0% { background-position: -200% 0; }
                  100% { background-position: 200% 0; }
                }
              `}</style>

              <SmartChatConsultant
                fashionAnalysis={state.fashionAnalysis}
              />
            </div>
          )}

          {/* Reports View */}
          {activeView === 'reports' && state.fashionAnalysis && (
            <div className="space-y-6">
              <div>
                <h1 className="text-3xl font-bold text-gray-900"> </h1>
                <p className="text-gray-600 mt-1">Silahkan Download laporan lengkap analisis bisnis kamu </p>
              </div>

              <Card>
                <CardHeader>
                  <CardTitle>📄 Ringkasan Laporan</CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <div className="grid md:grid-cols-2 gap-4">
                    <div>
                      <p className="text-sm text-gray-600">Nama File</p>
                      <p className="font-semibold">{state.fileName}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600">Tanggal Upload</p>
                      <p className="font-semibold">{state.uploadDate}</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600">Total Produk</p>
                      <p className="font-semibold">{state.fashionAnalysis.products.length} produk fashion</p>
                    </div>
                    <div>
                      <p className="text-sm text-gray-600">Total Penjualan</p>
                      <p className="font-semibold">{state.fashionAnalysis.totalUnits} unit terjual</p>
                    </div>
                  </div>

                  <div className="pt-4 border-t">
                    <Button onClick={handleDownloadReport} className="w-full md:w-auto bg-blue-900 hover:bg-blue-950">
                      <Download className="w-4 h-4 mr-2" />
                      Download Laporan Lengkap
                    </Button>
                    <p className="text-xs text-gray-500 mt-2">Format TXT - Bisa dibuka di HP/Laptop</p>
                  </div>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle>🎯 Insight Penting</CardTitle>
                </CardHeader>
                <CardContent>
                  <div className="space-y-2">
                    {state.fashionAnalysis.insights.map((insight, idx) => (
                      <div key={idx} className="flex items-start gap-2 p-3 bg-blue-50 rounded-lg border border-blue-100">
                        <span className="text-blue-600 font-bold mt-0.5">{idx + 1}.</span>
                        <p className="text-sm text-gray-700 flex-1">{insight}</p>
                      </div>
                    ))}
                  </div>
                </CardContent>
              </Card>
            </div>
          )}
        </div>
      </main>
    </div>
  );
};

export default DashboardLayout;
